files = ['mytabs.php','usersocial.php','myawards.php','myarcade.php','tlink.php','mybbirlastthreadsprofile.php','downloads.php',
		'recentthread.php','lpop.php','adminnotes.php','modnoteslog.php','changstats.php','recent_threads.php','newthreads.php',
		'thankyoulike.php','ougc_awards.php','ip_history_logs.php','trashbin.php','timeline_cp.php','threadredirect.php',
		'trends.php','deleteaccount.php','ougc_feedback.php']

myTabs = ["MyTabs", "1.32", "SQL Injection", "https://0day.today/exploit/16587"]
socialNetworks = ["User Social Networks", "1.2", "Cross-Site Scripting", "https://0day.today/exploit/22602"]
myAwards = ["MyAwards", "2.3", "CSRF", "https://www.exploit-db.com/exploits/39290/"]
myArcade = ["My Arcade", "1.3", "Cross-Site Scripting", "https://0day.today/exploit/29898"]
threadToLink = ["Threads to Link", "1.3", "Cross-Site Scripting", "https://0day.today/exploit/30230"]
lastThreadsProfile = ["Last User's Threads in Profile", "1.2", "Cross-Site Scripting", "https://0day.today/exploit/30049"]
downloads = ["Downloads", "2.0.3", "Cross-Site Scripting", "SQLi", "https://0day.today/exploit/30121", "https://0day.today/exploit/31498"]
recentThreadIndex = ["Recent Threads On Index", "17.0", "Cross-Site Scripting", "https://0day.today/exploit/30144"]
latestPostProfile = ["Latest Post on Profile", "1.1", "Cross-Site Scripting", "https://0day.today/exploit/30327"]
adminNotes = ["Admin Notes", "1.1", "Cross-Site Request Forgery", "https://0day.today/exploit/30363"]
modNotes = ["Moderator Log Notes", "1.1", "Cross-Site Scripting & CSRF", "https://0day.today/exploit/30460", "https://0day.today/exploit/30916"]
advancedStats = ["ChangUonDyU - Advanced Statistics", "1.0.2", "Cross-Site Scripting", "https://0day.today/exploit/30475"]
recentThreads = ["Recent Threads", "1.0", "Cross-Site Scripting", "https://0day.today/exploit/30533"]
newThreads = ["New Threads", "1.1", "Cross-Site Scripting", "https://0day.today/exploit/30751"]
thankyouLike = ["Thank You/Like", "3.0.0", "Cross-Site Scripting", "https://0day.today/exploit/30865"]
ougcAwards = ["OUGC Awards", "1.8.3", "Cross-Site Scripting", "https://0day.today/exploit/31881"]
ipLogs = ["User IP History Logs", "1.0.2", "Cross-Site Scripting", "https://0day.today/exploit/32079"]
trashbin = ["Trash Bin", "1.1.3", "Cross-Site Scripting & CSRF", "https://0day.today/exploit/32196"]
timeline = ["Timeline", "1.0", "Cross-Site Scripting & CSRF", "https://0day.today/exploit/35722"]
threadRedirect = ["Thread Redirect", "0.2.1", "Cross-Site Scripting", "https://0day.today/exploit/35765"]
trendWidget = ["Trending Widget", "1.2", "Cross-Site Scripting", "https://0day.today/exploit/35763"]
deleteAccount = ["Delete Account", "1.4", "Cross-Site Scripting", "https://0day.today/exploit/35764"]
ougcFeedback = ["OUGC Feedback", "1.8.22", "Cross-Site Scripting", "https://0day.today/exploit/35931"]