files = ['mytabs.php','usersocial.php','myawards.php','myarcade.php','tlink.php','mybbirlastthreadsprofile.php','downloads.php',
		'recentthread.php','lpop.php','adminnotes.php','modnoteslog.php','changstats.php','recent_threads.php','newthreads.php',
		'thankyoulike.php','ougc_awards.php','ip_history_logs.php','trashbin.php','timeline_cp.php','threadredirect.php',
		'trends.php','deleteaccount.php','ougc_feedback.php','upcoming_events.php','hidetillreply.php','activethreads.php',
        'iblinkwarning.php']

myTabs = ["MyTabs", "1.32", "SQL Injection", "https://www.exploit-db.com/exploits/36005"]
socialNetworks = ["User Social Networks", "1.2", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/34539"]
myAwards = ["MyAwards", "2.3", "CSRF", "https://www.exploit-db.com/exploits/39290"]
myArcade = ["My Arcade", "1.3", "Cross-Site Scripting", "https://packetstormsecurity.com/files/146590/MyBB-My-Arcade-1.3-Cross-Site-Scripting.html"]
threadToLink = ["Threads to Link", "1.3", "Cross-Site Scripting", "https://packetstormsecurity.com/files/147319/MyBB-Threads-To-Link-1.3-Cross-Site-Scripting.html"]
lastThreadsProfile = ["Last User's Threads in Profile", "1.2", "Cross-Site Scripting", "https://packetstormsecurity.com/files/146907/MyBB-Last-Users-Threads-In-Profile-1.2-Cross-Site-Scripting.html"]
downloads = ["Downloads", "2.0.3", "Cross-Site Scripting", "SQLi", "https://packetstormsecurity.com/files/147061/MyBB-Downloads-2.0.3-Cross-Site-Scripting.html", "https://packetstormsecurity.com/files/149993/MyBB-Downloads-2.0.3-SQL-Injection.html"]
recentThreadIndex = ["Recent Threads On Index", "17.0", "Cross-Site Scripting", "https://packetstormsecurity.com/files/147099/MyBB-Recent-Threads-On-Index-17.0-Cross-Site-Scripting.html"]
latestPostProfile = ["Latest Post on Profile", "1.1", "Cross-Site Scripting", "https://packetstormsecurity.com/files/147575/MyBB-Latest-Posts-On-Profile-1.1-Cross-Site-Scripting.html"]
adminNotes = ["Admin Notes", "1.1", "Cross-Site Request Forgery", "https://packetstormsecurity.com/files/147660/MyBB-Admin-Notes-1.1-Cross-Site-Request-Forgery.html"]
modNotes = ["Moderator Log Notes", "1.1", "Cross-Site Scripting & CSRF", "https://packetstormsecurity.com/files/147892/MyBB-Moderator-Log-Notes-1.1-Cross-Site-Scripting.html", "https://packetstormsecurity.com/files/148999/MyBB-Moderator-Log-Notes-1.1-Cross-Site-Request-Forgery.html"]
advancedStats = ["ChangUonDyU - Advanced Statistics", "1.0.2", "Cross-Site Scripting", "https://packetstormsecurity.com/files/147973/MyBB-ChangUonDyU-1.0.2-Cross-Site-Scripting.html"]
recentThreads = ["Recent Threads", "1.0", "Cross-Site Scripting", "https://packetstormsecurity.com/files/148046/MyBB-Recent-Threads-1.0-Cross-Site-Scripting.html"]
newThreads = ["New Threads", "1.1", "Cross-Site Scripting", "https://packetstormsecurity.com/files/148618/MyBB-New-Threads-1.1-Cross-Site-Scripting.html"]
thankyouLike = ["Thank You/Like", "3.0.0", "Cross-Site Scripting", "https://packetstormsecurity.com/files/148871/MyBB-Thank-You-Like-3.0.0-Cross-Site-Scripting.html"]
ougcAwards = ["OUGC Awards", "1.8.3", "Cross-Site Scripting", "https://packetstormsecurity.com/files/151016/MyBB-OUGC-Awards-1.8.3-Cross-Site-Scripting.html"]
ipLogs = ["User IP History Logs", "1.0.2", "Cross-Site Scripting", "https://packetstormsecurity.com/files/151359/MyBB-IP-History-Logs-1.0.2-Cross-Site-Scripting.html"]
trashbin = ["Trash Bin", "1.1.3", "Cross-Site Scripting & CSRF", "https://packetstormsecurity.com/files/151704/MyBB-Trash-Bin-1.1.3-Cross-Site-Request-Forgery-Cross-Site-Scripting.html"]
timeline = ["Timeline", "1.0", "Cross-Site Scripting & CSRF", "https://packetstormsecurity.com/files/161069/MyBB-Timeline-1.0-Cross-Site-Request-Forgery-Cross-Site-Scripting.html"]
threadRedirect = ["Thread Redirect", "0.2.1", "Cross-Site Scripting", "https://packetstormsecurity.com/files/161214/MyBB-Thread-Redirect-0.2.1-Cross-Site-Scripting.html"]
trendWidget = ["Trending Widget", "1.2", "Cross-Site Scripting", "https://packetstormsecurity.com/files/161215/MyBB-Trending-Widget-1.2-Cross-Site-Scripting.html"]
deleteAccount = ["Delete Account", "1.4", "Cross-Site Scripting", "https://packetstormsecurity.com/files/161216/MyBB-Delete-Account-1.4-Cross-Site-Scripting.html"]
ougcFeedback = ["OUGC Feedback", "1.8.22", "Cross-Site Scripting", "https://packetstormsecurity.com/files/161746/MyBB-OUGC-Feedback-1.8.22-Cross-Site-Scripting.html"]
upcomingEvents = ["Upcoming Events", "1.32", "Cross-Site Scripting", "https://packetstormsecurity.com/files/152152/MyBB-Upcoming-Events-1.32-Cross-Site-Scripting.html"]
hideThreadContent = ["Hide Thread Content", "1.0", "Broken Access Control", "https://packetstormsecurity.com/files/161185/MyBB-Hide-Thread-Content-1.0-Information-Disclosure.html"]
activeThreads = ["Active Threads", "1.3.0", "Cross-Site Scripting", "https://packetstormsecurity.com/files/171402/MyBB-Active-Threads-1.3.0-Cross-Site-Scripting.html"]
externalRedirectWarn = ["External Redirect Warning", "1.3", "Cross-Site Scripting", "https://packetstormsecurity.com/files/171403/MyBB-External-Redirect-Warning-1.3-Cross-Site-Scripting.html"]