files = ['mytabs.php','usersocial.php','myawards.php','myarcade.php','tlink.php','mybbirlastthreadsprofile.php','downloads.php',
		'recentthread.php','lpop.php','adminnotes.php','modnoteslog.php','changstats.php','recent_threads.php','newthreads.php',
		'thankyoulike.php','ougc_awards.php','ip_history_logs.php','trashbin.php','timeline_cp.php','threadredirect.php',
		'trends.php','deleteaccount.php','ougc_feedback.php']

myTabs = ["MyTabs", "1.32", "SQL Injection", "https://www.exploit-db.com/exploits/17595/"]
socialNetworks = ["User Social Networks", "1.2", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/34539/"]
myAwards = ["MyAwards", "2.3", "CSRF", "https://www.exploit-db.com/exploits/39290/"]
myArcade = ["My Arcade", "1.3", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/44186/"]
threadToLink = ["Threads to Link", "1.3", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/44547/"]
lastThreadsProfile = ["Last User's Threads in Profile", "1.2", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/44339/"]
downloads = ["Downloads", "2.0.3", "Cross-Site Scripting", "SQLi", "https://www.exploit-db.com/exploits/44400/", "https://www.exploit-db.com/exploits/45747/"]
recentThreadIndex = ["Recent Threads On Index", "17.0", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/44420/"]
latestPostProfile = ["Latest Post on Profile", "1.1", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/44608/"]
adminNotes = ["Admin Notes", "1.1", "Cross-Site Request Forgery", "https://www.exploit-db.com/exploits/44624/"]
modNotes = ["Moderator Log Notes", "1.1", "Cross-Site Scripting & CSRF", "https://www.exploit-db.com/exploits/44754/", "https://www.exploit-db.com/exploits/45224/"]
advancedStats = ["ChangUonDyU - Advanced Statistics", "1.0.2", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/44795/"]
recentThreads = ["Recent Threads", "1.0", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/44833/"]
newThreads = ["New Threads", "1.1", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/45057/"]
thankyouLike = ["Thank You/Like", "3.0.0", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/45178/"]
ougcAwards = ["OUGC Awards", "1.8.3", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/46080/"]
ipLogs = ["User IP History Logs", "1.0.2", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/46273/"]
trashbin = ["Trash Bin", "1.1.3", "Cross-Site Scripting & CSRF", "https://www.exploit-db.com/exploits/46384"]
timeline = ["Timeline", "1.0", "Cross-Site Scripting & CSRF", "https://www.exploit-db.com/exploits/49467"]
threadRedirect = ["Thread Redirect", "0.2.1", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/49505"]
trendWidget = ["Trending Widget", "1.2", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/49504"]
deleteAccount = ["Delete Account", "1.4", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/49500"]
ougcFeedback = ["OUGC Feedback", "1.8.22", "Cross-Site Scripting", "https://www.exploit-db.com/exploits/49635"]